#!/usr/bin/env bash
# This script displays formatted information from /etc/passwd

while IFS=: read -r username password userid groupid gecos homedir shell; do
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $userid"
done < /etc/passwd
